/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0jwgSdxKxkU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"

export function Managerdash() {
  return (
    (<div className="flex min-h-screen w-full flex-col bg-background">
      <header
        className="sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-background px-4 sm:px-6">
        <nav className="flex items-center gap-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <LogInIcon className="h-6 w-6" />
            <span className="font-bold">Learning Platform</span>
          </Link>
          <div className="hidden md:flex items-center gap-4">
            <Link href="#" className="font-medium hover:text-primary" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="font-medium hover:text-primary" prefetch={false}>
              Learning Modules
            </Link>
            <Link href="#" className="font-medium hover:text-primary" prefetch={false}>
              Exercises
            </Link>
            <Link href="#" className="font-medium hover:text-primary" prefetch={false}>
              Communication
            </Link>
            <Link href="#" className="font-medium hover:text-primary" prefetch={false}>
              Profile
            </Link>
          </div>
        </nav>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" className="rounded-full">
              <Avatar className="h-8 w-8">
                <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
                <AvatarFallback>JP</AvatarFallback>
              </Avatar>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuLabel>John Doe</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem>Settings</DropdownMenuItem>
            <DropdownMenuItem>Logout</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header>
      <div className="flex flex-1">
        <aside className="hidden w-64 flex-col border-r bg-background p-4 md:flex">
          <div className="flex items-center gap-4 border-b pb-4">
            <Avatar className="h-12 w-12">
              <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
              <AvatarFallback>JP</AvatarFallback>
            </Avatar>
            <div>
              <div className="font-medium">John Doe</div>
              <div className="text-sm text-muted-foreground">Student</div>
            </div>
          </div>
          <nav className="mt-4 flex flex-col gap-2">
            <Link
              href="#"
              className="flex items-center gap-2 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}>
              <HomeIcon className="h-5 w-5" />
              Dashboard
            </Link>
            <Link
              href="#"
              className="flex items-center gap-2 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}>
              <BookIcon className="h-5 w-5" />
              Learning Modules
            </Link>
            <Link
              href="#"
              className="flex items-center gap-2 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}>
              <ClipboardIcon className="h-5 w-5" />
              Exercises
            </Link>
            <Link
              href="#"
              className="flex items-center gap-2 rounded-md px-3 py-2 font-medium hover:bg-muted"
              prefetch={false}>
              <MessageCircleIcon className="h-5 w-5" />
              Communication
            </Link>
          </nav>
        </aside>
        <main className="flex-1 p-4 md:p-6">
          <div className="grid gap-6">
            <Card>
              <CardHeader>
                <CardTitle>Recent Lessons</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">Introduction to JavaScript</div>
                      <div className="text-sm text-muted-foreground">Completed 2 days ago</div>
                    </div>
                    <Button size="sm">Continue</Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">CSS Fundamentals</div>
                      <div className="text-sm text-muted-foreground">Completed 1 week ago</div>
                    </div>
                    <Button size="sm">Continue</Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">HTML Basics</div>
                      <div className="text-sm text-muted-foreground">Completed 2 weeks ago</div>
                    </div>
                    <Button size="sm">Continue</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Continue Learning</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">React Fundamentals</div>
                      <div className="text-sm text-muted-foreground">Last accessed 3 days ago</div>
                    </div>
                    <Button size="sm">Continue</Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">SQL Basics</div>
                      <div className="text-sm text-muted-foreground">Last accessed 1 week ago</div>
                    </div>
                    <Button size="sm">Continue</Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">Python for Beginners</div>
                      <div className="text-sm text-muted-foreground">Last accessed 2 weeks ago</div>
                    </div>
                    <Button size="sm">Continue</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle>Quizzes</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">JavaScript Quiz</div>
                      <div className="text-sm text-muted-foreground">Completed 2 days ago</div>
                    </div>
                    <Button size="sm">Review</Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">CSS Quiz</div>
                      <div className="text-sm text-muted-foreground">Completed 1 week ago</div>
                    </div>
                    <Button size="sm">Review</Button>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium">HTML Quiz</div>
                      <div className="text-sm text-muted-foreground">Completed 2 weeks ago</div>
                    </div>
                    <Button size="sm">Review</Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>
        <aside className="hidden w-64 flex-col border-l bg-background p-4 md:flex">
          <Card>
            <CardHeader>
              <CardTitle>Notifications</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-start gap-3">
                  <div
                    className="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-primary-foreground">
                    <BellIcon className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="font-medium">New Assignment</div>
                    <div className="text-sm text-muted-foreground">You have a new assignment due tomorrow.</div>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div
                    className="flex h-8 w-8 items-center justify-center rounded-full bg-accent text-accent-foreground">
                    <CalendarIcon className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="font-medium">Upcoming Quiz</div>
                    <div className="text-sm text-muted-foreground">You have a quiz scheduled for next week.</div>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <div
                    className="flex h-8 w-8 items-center justify-center rounded-full bg-secondary text-secondary-foreground">
                    <MessageCircleIcon className="h-5 w-5" />
                  </div>
                  <div>
                    <div className="font-medium">New Message</div>
                    <div className="text-sm text-muted-foreground">You have a new message from your teacher.</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="mt-4">
            <CardHeader>
              <CardTitle>Progress</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div className="font-medium">Lessons Completed</div>
                  <div>12/20</div>
                </div>
                <Progress value={60} aria-label="Lessons Completed" />
                <div className="flex items-center justify-between">
                  <div className="font-medium">Quizzes Passed</div>
                  <div>8/10</div>
                </div>
                <Progress value={80} aria-label="Quizzes Passed" />
              </div>
            </CardContent>
          </Card>
        </aside>
      </div>
    </div>)
  );
}

function BellIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>)
  );
}


function BookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>)
  );
}


function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function ClipboardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path
        d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function LogInIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>)
  );
}


function MessageCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>)
  );
}
