/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/PgdjuJGcCQh
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Chivo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Button } from "@/components/ui/button"
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem } from "@/components/ui/dropdown-menu"
import { TooltipProvider, Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"

export function Teacherdash() {
  return (
    (<div className="flex min-h-screen w-full flex-col bg-muted/40">
      <header
        className="sticky top-0 z-30 flex h-14 items-center gap-4 border-b bg-background px-4 sm:static sm:h-auto sm:border-0 sm:bg-transparent sm:px-6">
        <Sheet>
          <SheetTrigger asChild>
            <Button size="icon" variant="outline" className="sm:hidden">
              <MenuIcon className="h-5 w-5" />
              <span className="sr-only">Toggle Menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="left" className="sm:max-w-xs">
            <div className="grid gap-6 px-6 py-8">
              <div className="flex items-center gap-4">
                <img
                  src="/placeholder.svg"
                  width={48}
                  height={48}
                  alt="Avatar"
                  className="rounded-full"
                  style={{ aspectRatio: "48/48", objectFit: "cover" }} />
                <div>
                  <p className="text-lg font-medium">John Doe</p>
                  <p className="text-sm text-muted-foreground">Student</p>
                </div>
              </div>
              <nav className="grid gap-2">
                <Link
                  href="#"
                  className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}>
                  <HomeIcon className="h-5 w-5" />
                  Home
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}>
                  <BookIcon className="h-5 w-5" />
                  Learning Modules
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}>
                  <ClipboardIcon className="h-5 w-5" />
                  Exercises
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}>
                  <MessageCircleIcon className="h-5 w-5" />
                  Communication
                </Link>
                <Link
                  href="#"
                  className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground"
                  prefetch={false}>
                  <UserIcon className="h-5 w-5" />
                  Profile
                </Link>
              </nav>
            </div>
          </SheetContent>
        </Sheet>
        <nav className="hidden gap-5 text-sm font-medium sm:flex">
          <Link href="#" className="font-bold" prefetch={false}>
            Home
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Learning Modules
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Exercises
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Communication
          </Link>
          <Link href="#" className="text-muted-foreground" prefetch={false}>
            Profile
          </Link>
        </nav>
        <div className="ml-auto flex items-center gap-2">
          <Button variant="outline" size="icon" className="rounded-full">
            <SignalIcon className="h-5 w-5" />
            <span className="sr-only">Notifications</span>
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="icon" className="overflow-hidden rounded-full">
                <img
                  src="/placeholder.svg"
                  width={36}
                  height={36}
                  alt="Avatar"
                  className="overflow-hidden rounded-full"
                  style={{ aspectRatio: "36/36", objectFit: "cover" }} />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>My Account</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Settings</DropdownMenuItem>
              <DropdownMenuItem>Support</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>Logout</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <div className="flex flex-1 sm:gap-4 sm:py-4 sm:pl-14">
        <aside
          className="fixed inset-y-0 left-0 z-10 hidden w-14 flex-col border-r bg-background sm:flex">
          <nav className="flex flex-col items-center gap-4 px-2 sm:py-5">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Link
                    href="#"
                    className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
                    prefetch={false}>
                    <UserIcon className="h-5 w-5" />
                    <span className="sr-only">Students</span>
                  </Link>
                </TooltipTrigger>
                <TooltipContent side="right">Students</TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Link
                    href="#"
                    className="flex h-9 w-9 items-center justify-center rounded-lg bg-accent text-accent-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
                    prefetch={false}>
                    <SchoolIcon className="h-5 w-5" />
                    <span className="sr-only">Teachers</span>
                  </Link>
                </TooltipTrigger>
                <TooltipContent side="right">Teachers</TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Link
                    href="#"
                    className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
                    prefetch={false}>
                    <GroupIcon className="h-5 w-5" />
                    <span className="sr-only">Parents</span>
                  </Link>
                </TooltipTrigger>
                <TooltipContent side="right">Parents</TooltipContent>
              </Tooltip>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Link
                    href="#"
                    className="flex h-9 w-9 items-center justify-center rounded-lg text-muted-foreground transition-colors hover:text-foreground md:h-8 md:w-8"
                    prefetch={false}>
                    <BriefcaseIcon className="h-5 w-5" />
                    <span className="sr-only">HR Professionals</span>
                  </Link>
                </TooltipTrigger>
                <TooltipContent side="right">HR Professionals</TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </nav>
        </aside>
        <main className="flex-1 p-4 sm:px-6 sm:py-0">
          <div className="grid gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Learning Modules</CardTitle>
                <CardDescription>Explore the latest learning modules.</CardDescription>
              </CardHeader>
              <CardContent>
                <div
                  className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
                  <Link
                    href="#"
                    className="group flex flex-col items-start gap-2 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                    prefetch={false}>
                    <BookIcon
                      className="h-8 w-8 text-muted-foreground group-hover:text-accent-foreground" />
                    <div className="text-sm font-medium">Module 1</div>
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      Introduction to the fundamentals of web development.
                    </p>
                  </Link>
                  <Link
                    href="#"
                    className="group flex flex-col items-start gap-2 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                    prefetch={false}>
                    <BookIcon
                      className="h-8 w-8 text-muted-foreground group-hover:text-accent-foreground" />
                    <div className="text-sm font-medium">Module 2</div>
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      Dive into HTML and CSS for building responsive layouts.
                    </p>
                  </Link>
                  <Link
                    href="#"
                    className="group flex flex-col items-start gap-2 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                    prefetch={false}>
                    <BookIcon
                      className="h-8 w-8 text-muted-foreground group-hover:text-accent-foreground" />
                    <div className="text-sm font-medium">Module 3</div>
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      Explore JavaScript and its role in creating interactive web applications.
                    </p>
                  </Link>
                  <Link
                    href="#"
                    className="group flex flex-col items-start gap-2 rounded-md bg-background p-4 transition-colors hover:bg-accent hover:text-accent-foreground"
                    prefetch={false}>
                    <BookIcon
                      className="h-8 w-8 text-muted-foreground group-hover:text-accent-foreground" />
                    <div className="text-sm font-medium">Module 4</div>
                    <p className="text-sm text-muted-foreground line-clamp-2">
                      Understand the principles of responsive design and accessibility.
                    </p>
                  </Link>
                </div>
              </CardContent>
            </Card>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
              <Card>
                <CardHeader>
                  <CardTitle>Progress</CardTitle>
                  <CardDescription>Track your learning progress.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="flex items-center justify-between">
                      <div className="text-sm font-medium">Modules Completed</div>
                      <div className="text-2xl font-bold">2/4</div>
                    </div>
                    <Progress value={50} aria-label="50% modules completed" />
                    <div className="flex items-center justify-between">
                      <div className="text-sm font-medium">Exercises Completed</div>
                      <div className="text-2xl font-bold">12/20</div>
                    </div>
                    <Progress value={60} aria-label="60% exercises completed" />
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Upcoming Assignments</CardTitle>
                  <CardDescription>View your upcoming assignments.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="flex items-center justify-between">
                      <div className="text-sm font-medium">Web Development Project</div>
                      <div className="text-sm text-muted-foreground">Due: May 15</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="text-sm font-medium">UI Design Challenge</div>
                      <div className="text-sm text-muted-foreground">Due: June 1</div>
                    </div>
                    <div className="flex items-center justify-between">
                      <div className="text-sm font-medium">JavaScript Algorithms</div>
                      <div className="text-sm text-muted-foreground">Due: June 30</div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>Notifications</CardTitle>
                  <CardDescription>Stay up-to-date with the latest updates.</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="flex items-start gap-3">
                      <div
                        className="flex h-8 w-8 items-center justify-center rounded-full bg-blue-500 text-white">
                        <SignalIcon className="h-4 w-4" />
                      </div>
                      <div>
                        <p className="text-sm font-medium">New Learning Module Available</p>
                        <p className="text-sm text-muted-foreground">Check out the latest module on React.</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <div
                        className="flex h-8 w-8 items-center justify-center rounded-full bg-green-500 text-white">
                        <CheckIcon className="h-4 w-4" />
                      </div>
                      <div>
                        <p className="text-sm font-medium">Congratulations!</p>
                        <p className="text-sm text-muted-foreground">You've completed the HTML and CSS module.</p>
                      </div>
                    </div>
                    <div className="flex items-start gap-3">
                      <div
                        className="flex h-8 w-8 items-center justify-center rounded-full bg-yellow-500 text-white">
                        <BadgeAlertIcon className="h-4 w-4" />
                      </div>
                      <div>
                        <p className="text-sm font-medium">Upcoming Deadline</p>
                        <p className="text-sm text-muted-foreground">
                          Don't forget to submit your JavaScript project by June 15.
                        </p>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </main>
        <aside className="hidden w-64 flex-col gap-4 p-4 sm:flex">
          <Card>
            <CardHeader>
              <CardTitle>Upcoming Events</CardTitle>
              <CardDescription>Check out the latest events and workshops.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4">
                <div className="flex items-start gap-3">
                  <div className="flex h-8 w-8 items-center justify-center" />
                </div>
              </div>
            </CardContent>
          </Card>
        </aside>
      </div>
    </div>)
  );
}

function BadgeAlertIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </svg>)
  );
}


function BookIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>)
  );
}


function BriefcaseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>)
  );
}


function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}


function ClipboardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="8" height="4" x="8" y="2" rx="1" ry="1" />
      <path
        d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>)
  );
}


function GroupIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 7V5c0-1.1.9-2 2-2h2" />
      <path d="M17 3h2c1.1 0 2 .9 2 2v2" />
      <path d="M21 17v2c0 1.1-.9 2-2 2h-2" />
      <path d="M7 21H5c-1.1 0-2-.9-2-2v-2" />
      <rect width="7" height="5" x="7" y="7" rx="1" />
      <rect width="7" height="5" x="10" y="12" rx="1" />
    </svg>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MessageCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
    </svg>)
  );
}


function SchoolIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M14 22v-4a2 2 0 1 0-4 0v4" />
      <path d="m18 10 4 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-8l4-2" />
      <path d="M18 5v17" />
      <path d="m4 6 8-4 8 4" />
      <path d="M6 5v17" />
      <circle cx="12" cy="9" r="2" />
    </svg>)
  );
}


function SignalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>)
  );
}


function UserIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>)
  );
}
